//SOLUTION NUMBER 1

let A = "DEEPU" 
let b = 6

console.log( A + b) 

//solution  2

console.log(typeof A + b) 

//solution 3

const  a = {
    name : "deepu",
    section: 1,
    isprincipal : false,
}
// a = "deepu" //syntax error


//solution 4

a1['friend'] = "shubham"
console.log(a1)


//solution 5

const dict = {
    appreciate: "recognize the full worth of. jai ho .",
    atarapre: "jai hind jai bharat jai ho jai jawan jai kisan ",
    yakka:"works , specially hard work "
}

console.log('yakka')