let a = document.getElementsByName('div')[0]
// a.innerHTML = a.innerHTML = <h1>HEllow deepu sir Wlcm to  in your under bla.. bla.. bla..</h1>
let div = document.createElement('div');
// div.innerHTML = <h1>Hellow world</h1>;
// a.appendChild(div);
a.append(div)
a.prepend(div)
a.before(div)
a.after(div)
a.replaceWith(div)

// let div = document.createElement('div')   //created
// div.className = alert("hello deepu sir") //alert

// // div.innerHTML = <span> jai hind jai bharat </span>


// document.body.append(div)
// undefined
// document.body.prepend(div)
// undefined
// document.body.before(div)
// undefined
// document.body.after(div)
// undefined
// document.body.replaceWith(div)
// undefined