// function name(params) {
    
// }


// async function name(params) {
    
// }


// // async (params) => {
    
// // }

// // let a = 9
// // let i = 5
// // function a(){
// //     if (i<a) {
// //         console.log("hurrey its wrong ")
// //     }
// //     else{
// //         console.log("thats true ")
// //     }
// // }


// let sum = (a,b)=>{
//     let c = a+b;
//     return c
// }


// let y = sum (1,3)

//ooper sab galat hai ye sab mai khud se khurapti kar raha tha harry sir ka lecture neeche se start  hai maine soch run hoga nahi hua 


let a = 1;
let b = 2;
let c = 3;

console.log("Sum of the value a and b is and get a chance to win " ,(a + b)/2,"hurrey ye ho gaya")
console.log("done")
console.log("Sum of the value a and c is and get a chance to win " ,(a + b)/2,"hurrey ye ho gaya")
console.log("done")
console.log("Sum of the value c and b is and get a chance to win " ,(a + b)/2,"hurrey ye ho gaya")
console.log("done")



function sum  (a=2,b=100){
    console.log(a,b)
    return 1 + (a * b)
}
console.log("Sum of the value c and b is and get a chance to win " ,+ sum +(a + b)/2,"hurrey ye ho gaya")

