deepu.insertAdjacentHTML('boforebegin','<div class="test">beforeend</div>');    // beforebegin
deepu.insertAdjacentHTML('afterbegin','<div class="test">beforeend</div>');     // afterbegin
deepu.insertAdjacentHTML('boforeend','<div class="test">beforeend</div>');      // beforeend
deepu.insertAdjacentHTML('afterend','<div class="test">beforeend</div>');       // afterend

deepu.remove(); // remove the element