setTimeout(()=>{
    console.log("Hacking WiFi Please Wait....")
},1000);

try {
    console.log(Rahul)
} catch (error) {
    console.log("this is a error")
}

setTimeout(()=>{
    console.log("Fetching User name and Passwords... Please Wait...")
},3000)
try{
    console.log(hdfjhsdjkfh)
}

setTimeout(()=>{
    console.log("Hacking rahuls phone ... Please Wait...")
},5000)

setTimeout(()=>{
    console.log("Hacking Rahul's WiFi ... Please Wait...")
},7000)

setTimeout(()=>{
    console.log("Hacking rahul's all DATA...")
},9000)