//WHAT IS PROMISE?
//~ Promise is an object that may produce a single value some time in the future: either a resolved value, or a reason that it’s not resolved (e.g., a network error occurred). A promise may be in one of 3 possible states: fulfilled, rejected, or pending. Promise users can attach callbacks to handle the fulfilled value or the reason for rejection.

//EXAMPLE OF Promise
console.log("Promise Example");
setTimeout(function(){
    console.log("Inside setTimeout");
},1000);
console.log("Outside setTimeout" + john);



let promise = new promise(function(resolve,reject){
alert("i am an alert in promise" )
});
console.log(promise);