let ctitle = document.getElementsByName("card-title")[0];
// ctitle.style.color = 'black'

let firstcardtitle = document.getElementById("firstcardtitle")
firstcardtitle.style.color = 'blue'

// let clol = docum log(...data: any[]): void title)
// console.log(clol);

let clol = document.querySelectorAll('.card-title')
clol[0].style.color = 'blue';
clol[1].style.color = 'red';
clol[2].style.color = 'green';

console.log(clol);


document.querySelector('yes').style.color = 'blue';