let name = "deepu\",\n,\r,bhai"
let friend = "arsh"
let friend2 = "       khushi         "
let fr = "shivika"
console.log(name)
console.log(name.length)
console.log(name.toUpperCase())
console.log(name.toLowerCase())
console.log(name.slice(2,4))
console.log(name.replace('bhai' , 'bhai'))
console.log(name.concat(" is a friend of ", friend," ok "))
console.log(friend2.trim())
console.log(fr[0])
console.log(fr[1])
console.log(fr[2])
console.log(fr[3])

//QUICKQUIZ: Use a for loop to print a string

for (let i = 0; name < 5; i++) {
    console.log(friend2 ,+ "Printed");
}