let deepuForm = new RailwayForm()

let RohanForm1 = new RailwayForm()
let RohanForm2 = new RailwayForm();
RohanForm1.submit()
RohanForm2.submit()










// class Car {
//     constructor(brand, model, color) {
//       this.brand = brand;
//       this.model = model;
//       this.color = color;
//     }
  
//     start() {
//       console.log(`${this.brand} ${this.model} is starting... 🚗💨`);
//     }
//   }
//   const car1 = new Car("Toyota", "Camry", "Red");
// const car2 = new Car("BMW", "X5", "Black");

// console.log(car1.brand); // Toyota
// console.log(car2.model); // X5

// car1.start(); // Toyota Camry is starting... 🚗💨
// car2.start(); // BMW X5 is starting... 🚗💨








// class Car {
//     constructor(Brand,model,Color, ) {
//         this.Brand = Brand;
//         this.model = model;
//         this.Color = Color;
//     }
//     start(){
//         console.log(`${this.Brand} ${this.model} ${this.Color}`);
//     }
// }

// Brand = ("BMW", "CAMLY","MESRATI", "MECEDES", "RR","PORCHE", "OPEN JEEP THAR" );
// model = ("2010", "2011","2012","2013","2014", "2015", "2020", "2021", "2022");
// Color = ("blue")