
// console.log(document.getElementsByTagName('span')[0])
// console.dir(document.getElementsByTagName('span')[0])

console.log(document.body.firstChild.nodeName)
console.log(document.body.firstElementChild.nodeName)

first.innerHTML = '<i>Hey I am italy</i>'
first.outerHTML //'<span id="first"><i>Hey I am italy</i></span>'

first.outerHTML = '<div>Hey</div>'

document.body.firstChild.data

document.body.firstChild.nodeValue


console.log(document.body.textContent)

$0.hidden = false
$0.hidden = true



// console.log(console.dir)
// console.dir
// document.getElementsByTagName
// document.body.innerHTML(<div hidden>I am hidden</div>)
// texcontant

// //the hidden property