// class complex {
//     constructor(real, imaginary) {
//         this.real = real;
//         this.imaginary = this.imaginary
//     }
//     add(num){
//        this.real = this.real + num.real
//         this.imaginary = this.imaginary + num.imaginary
//         return new complex(r, i)
//     }
// }

// let a = new complex(2, 3)
// let b = new complex(6, 2)
// a.add(b)
// console.log(a.real, a.imaginary)


// class deepu {
//     constructor(name) {
//         this.name = name;
//     }
//     ll
// }



//2. 
// class Human {
//     constructor(name, favFood) {
//         this.name = name
//         this.favFood = favFood
//     }walk(){
//         console.log(this.name + "Human is walking")
//     }
// }

// class students extends Human {
//     walk(){
//         console.log(this.name + "Human is walking")
//     }
        
//     }
// let o = new students()
// o.walk()
