// ARRAY METHOD
 
let num = [1,2,3,34,4]
let b = num.toString() //b is now a string
console.log(b, typeof b)

let c = num.join(' - ') //c is now a string
console.log(c , typeof c)

let d = num.pop() //d is now a number 
console.log(num, d)

let e = num.push(5,6) //e is now a number
console.log(num, e)

let f = num.shift() //f is now a number
console.log(num. f)

let g = num.unshift(7,8) //g is now a number
console.log(num, g)

