let t = document.body.firstElementChild.firstElementChild
console.log(t.rows) // #;



/*
table.rows  // Returns a collection of all <tr> elements in the table
table.caption // Returns the first <caption> element in the table
table.tHead // Returns the <thead> element in the table
table.tFoot // Returns the <tfoot> element in the table
table.tBodies // Returns a collection of all <tbody> elements in the table
table.rows[0] // Returns the first <tr> element of the table

tr.cells // Returns a collection of all <td> or <th> elements in the row
tr.sectionRowIndex // Returns the position of the row in the table section
tr.rowIndex // Returns the position of the row in the table

td.cellIndex // Returns the position of the cell in the row
*/