// chapter - 2 - 
// problem 1

// let age = prompt("what is your age");  //prompt is not running on vscode
// if(age>10 && age<=20){
//     console.log("your age lies between 10 and 20")
// }
// else{
//     console.log("your age dosnt b/w 10 and 20")
// }


// problem no 3
/*
console.log("your age lies between"(a>10?"10 and 20 ":age<=20?"10 and 20"));

let age = Number.parseInt("what is your age");  //prompt is not running on vscode
switch(age){
    case 12:
        console.log("age is 12")
        break;
    case 13:
        console.log("age is 13")
        break;
    case 14:
        console.log("age is 14")
        break;
    case 15:
        console.log("age is 15")
        break;
    default:
    console.log("your age is not special")
}*/

//problem no. 4

// let num = prompt("what id your age?")
// num = Number.parseInt(num)
// if(num%2==0 && num%3==0){
//     console.log("your number is divided by 2 and 3")
// }
// else {
//     console.log("your number is not divided by 2 and 3")
// }

//problem no. 5

let age = 17
let a = age >18 ? "you can drive": "you can not drive"
console.log(a)

//wrong code solved
//tareeka 1
// let drive = prompt("you can drive or not")
// if(drive<18){
//     console.log("you can not drive")
// }
// else(drive>=18){
//     console.log("you can drive")
// }

//tareeka 2
// let age = prompt("whats your age")
// num = Number.parseInt(age)
// if(age<18"you can drive" : age>=18"you can drive")