// nn bb ss u
let a = null ;
let b = 345;
let c = true; // can also be false 
let d = BigInt("567") + BigInt("3")
let f = Symbol("I am a nice Symbol")
let g = undefined
    let G //UNDEFINED

console.log(a,b,c,d,f,g)
console.log(typeof a, typeof b,typeof c,typeof d,typeof f,typeof g)

//OBJECT IN JS

const ITEM = {
    "DEEPU": true,
    "SHUBH": false,
    "LOVISH": 67,
    "ROHAN":undefined,
}
console.log(ITEM["DEEPU"])
console.log(ITEM["SHUBH"])
console.log(ITEM["67"]) //UNDEFINED
console.log(ITEM["ROHAN"])

