let name = "deepu"
console.log(name)
console.log(name.length)
console.log(name[0])
console.log(name[1])
console.log(name[2])
console.log(name[3])
console.log(name[4])
console.log(name[0,1,2,3,4]) //i dont know why its not working but i think this code is right hahahahaha!


let boy1 = "abhishek"
let boy2 = "arsh"
let sentence = `${boy1}" is a friend of "${boy2}`

// Escape Sequence Characters
let fruite = 'bana \'na ,bana \n na '  // ~ \'its fixes a error and print a = bana 'na / \n newline
console.log(fruite)
console.log(fruite.length)
