let name = "deepu yadav don bhai gunda villin hero "

console.log(name.length)
console.log(name[5])
console.log(name[4])
console.log(name[3])
console.log(name[2])
console.log(name[1])

let names = 'deepy.x7'

let deepu = `depanshu`

let sentence = `the name "is" ${names}`

console.log(sentence)


let named = `deepu\'s`
console.log(named)

let ram = ` bhagwan \n and bhagwan is a ram \t isiliye hamehsa bolo jai shree ram \r i am a worlds most richest man `
console.log(ram)


let d = "deepu"
console.log(d.length)
console.log(d.toLowecase())
console.log(d.toUppercase())
console.log(d.slice())


