//DONT USE THE CALL FUNCTION BECAUSE CALLBACK FUNCTION ALWAYS REURN A COMPLEXIBILITY
//ALWAYS USE THE PROMISE AND ASYNC AWAIT FUNCTION BECAUSE IT IS EASY TO USE AND UNDERSTAND AND REDUCE THE COMPLEXIBILITY
//CALLBACK FUNCTION IS USED IN THE OLDER VERSION OF JAVASCRIPT
//PROMISE AND ASYNC AWAIT FUNCTION IS USED IN THE NEW VERSION OF JAVASCRIPT

//what is pyramide of doom
//~ it is a situation where you have multiple nested callback functions
//what is callback hell 
//~ it is a situation where you have multiple nested callback functions
//what is callback function
//~ a callback function is a function that is passed as an argument to another function